services:
  postgres:
    command:
      - "postgres"
    container_name: "postgres"
    entrypoint:
      - "docker-entrypoint.sh"
    environment:
      - "PG_VERSION=17.2-1.pgdg120+1"
      - "PGDATA=/var/lib/postgresql/data"
      - "POSTGRES_PASSWORD=St@rCraft#22F0x"
      - "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/lib/postgresql/17/bin"
      - "GOSU_VERSION=1.17"
      - "LANG=en_US.utf8"
      - "PG_MAJOR=17"
    hostname: "postgres"
    image: "postgres:17.2-alpine"
    logging:
      driver: "json-file"
      options: {}
    networks:
      carsties:
        ipv4_address: 10.10.10.2
    ports:
      - "5432:5432/tcp"
    volumes:
      - "postgres_data:/var/lib/postgresql/data"

  rabbitmq_with_management:
    command:
      - "rabbitmq-server"
    container_name: "rabbitmq_with_management"
    entrypoint:
      - "docker-entrypoint.sh"
    environment:
      - "PATH=/opt/rabbitmq/sbin:/opt/erlang/bin:/opt/openssl/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      - "ERLANG_INSTALL_PATH_PREFIX=/opt/erlang"
      - "OPENSSL_INSTALL_PATH_PREFIX=/opt/openssl"
      - "RABBITMQ_DATA_DIR=/var/lib/rabbitmq"
      - "RABBITMQ_PGP_KEY_ID=0x0A9AF2115F4687BD29803A206B73A36E6026DFCA"
      - "RABBITMQ_HOME=/opt/rabbitmq"
      - "HOME=/var/lib/rabbitmq"
      - "LANG=C.UTF-8"
      - "LANGUAGE=C.UTF-8"
      - "LC_ALL=C.UTF-8"
    hostname: "rabbitmq"
    image: "rabbitmq:4.0.5-management-alpine"
    logging: 
      driver: "json-file"
      options: {}
    networks:
      carsties:
        ipv4_address: 10.10.10.3
    ports:
      - "15671:15672/tcp"
      - "5672:5672/tcp"
    volumes:
      - "rabbitmq_data:/var/lib/rabbitmq"
    working_dir: "/"

  ravendb:
    command:
      - "/bin/bash"
      - "/usr/lib/ravendb/scripts/run-raven.sh"
    container_name: "ravendb"
    environment:
      - "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      - "APP_UID=1654"
      - "ASPNETCORE_HTTP_PORTS=8080"
      - "DOTNET_RUNNING_IN_CONTAINER=true"
      - "RAVEN_ARGS="
      - "RAVEN_SETTINGS="
      - "RAVEN_IN_DOCKER=true"
      - "RAVEN_Setup_Mode=Initial"
      - "RAVEN_ServerUrl_Tcp=38888"
      - "RAVEN_AUTO_INSTALL_CA=true"
      - "RAVEN_DataDir=/var/lib/ravendb/data"
      - "RAVEN_Indexing_NugetPackagesPath=/var/lib/ravendb/nuget"
      - "RAVEN_Logs_Path=/var/log/ravendb/logs"
      - "RAVEN_Security_AuditLog_FolderPath=/var/log/ravendb/audit"
      - "RAVEN_Security_MasterKey_Path=/etc/ravendb/security/master.key"
      - "RAVEN_Setup_Certificate_Path=/etc/ravendb/security/server.pfx"
      - "RAVEN_Security_UnsecuredAccessAllowed=PrivateNetwork"
    hostname: "ravendb"
    image: "ravendb/ravendb:latest"
    labels:
      org.opencontainers.image.ref.name: "ubuntu"
      org.opencontainers.image.version: "22.04"
    networks:
      carsties:
        ipv4_address: 10.10.10.4
    logging:
      driver: "json-file"
      options: {}
    ports:
      - "161:161/tcp"
      - "38888:38888/tcp"
      - "8080:8080/tcp"
    user: "ravendb:ravendb"
    volumes:
      - "ravendb_etc:/etc/ravendb"
      - "ravendb_data:/var/lib/ravendb/data"
    working_dir: "/usr/lib/ravendb"
    
  auctions_service_api:
    build:
        context: "./src/AuctionService/AuctionService.API"
        dockerfile: Dockerfile
    container_name: "auctions_service_api"
    hostname: "auction_service_api"
    depends_on:
        - postgres
        - rabbitmq_with_management
        - identity_service
    image: "auctionserviceapi:latest"
    ports:
        - "7016:8080"
    networks:
      carsties:
        ipv4_address: 10.10.10.5

  search_service_api:
    build:
      context: "./src/SearchService/SearchService.API"
      dockerfile: Dockerfile
    container_name: "search_service_api"
    hostname: "search_service_api"
    depends_on:
      - ravendb
      - rabbitmq_with_management
    image: "searchserviceapi:latest"
    ports:
      - "7017:8080"
    networks:
      carsties:
        ipv4_address: 10.10.10.6

  identity_service:
    build:
      context: "./src/IdentityService"
      dockerfile: Dockerfile
    container_name: "identity_service"
    hostname: "identity_service"
    depends_on:
      - postgres
    image: "identityservice:latest"
    ports:
      - "7018:8080"
    networks:
      carsties:
        ipv4_address: 10.10.10.7

  gateway_service:
    build:
      context: "./src/GatewayService"
      dockerfile: Dockerfile
    container_name: "gateway_service"
    hostname: "gateway_service"
    image: "gatewayservice:latest"
    ports:
      - "5050:8080"
    networks:
      carsties:
        ipv4_address: 10.10.10.8

networks:
  carsties:
    ipam:
      config:
        - subnet: "10.10.10.0/24"

volumes:
  ravendb_etc:
  rabbitmq_data:
  postgres_data:
  ravendb_data: